### PR TITLE
Arrowhead touchups

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request

touches the arrowhead
- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
ship better

## Changelog

:cl:
tweak: Modified the arrowhead slightly.
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Touching???????

**Comment by TheNeoGamer42** [comment]
shutup

**Comment by TheNeoGamer42** [comment]
why is mapdiffbot broke

**Comment by Ms-Mee** [comment]
It wasn't me I didn't touch it I- *explodes

**Comment by TheNeoGamer42** [comment]
:waa:

**Comment by TheNeoGamer42** [comment]
now the question is do I speedrun merge my own PR

**Pull request merged**
